.TH "Содержание директории obj/x64/Debug/net5.0-windows" 3 "Enigma Machine Sumulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории obj/x64/Debug/net5.0-windows
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fB\&.NETCoreApp,Version=v5\&.0\&.AssemblyAttributes\&.cs\fP"
.br
.ti -1c
.RI "файл \fBEnigma2\&.AssemblyInfo\&.cs\fP"
.br
.in -1c
