.TH "Содержание директории EnigmaMachineSimulator/Core" 3 "Enigma Machine Sumulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории EnigmaMachineSimulator/Core
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBBaseEnigma\&.cs\fP"
.br
.ti -1c
.RI "файл \fBELabel\&.cs\fP"
.br
.ti -1c
.RI "файл \fBPlugboard\&.cs\fP"
.br
.ti -1c
.RI "файл \fBSettingsForm\&.cs\fP"
.br
.ti -1c
.RI "файл \fBSettingsForm\&.Designer\&.cs\fP"
.br
.in -1c
