.TH "Enigma2.Settings" 3 "Enigma Machine Sumulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Enigma2.Settings
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "int[] \fBkey\fP"
.br
.ti -1c
.RI "int[] \fBring\fP"
.br
.ti -1c
.RI "int[] \fBrotors\fP"
.br
.ti -1c
.RI "bool \fBcustomReflector\fP"
.br
.ti -1c
.RI "string \fBreflector\fP"
.br
.ti -1c
.RI "float \fBsound\fP"
.br
.ti -1c
.RI "bool \fBuseM4\fP"
.br
.ti -1c
.RI "Dictionary< char, char > \fBreplace\fP"
.br
.ti -1c
.RI "int \fBreflIndex\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле \fBSettingsForm\&.cs\fP строка \fB231\fP
.SH "Данные класса"
.PP 
.SS "bool Enigma2\&.Settings\&.customReflector"

.PP
См\&. определение в файле \fBSettingsForm\&.cs\fP строка \fB236\fP
.SS "int [] Enigma2\&.Settings\&.key"

.PP
См\&. определение в файле \fBSettingsForm\&.cs\fP строка \fB233\fP
.SS "string Enigma2\&.Settings\&.reflector"

.PP
См\&. определение в файле \fBSettingsForm\&.cs\fP строка \fB237\fP
.SS "int Enigma2\&.Settings\&.reflIndex"

.PP
См\&. определение в файле \fBSettingsForm\&.cs\fP строка \fB241\fP
.SS "Dictionary<char, char> Enigma2\&.Settings\&.replace"

.PP
См\&. определение в файле \fBSettingsForm\&.cs\fP строка \fB240\fP
.SS "int [] Enigma2\&.Settings\&.ring"

.PP
См\&. определение в файле \fBSettingsForm\&.cs\fP строка \fB234\fP
.SS "int [] Enigma2\&.Settings\&.rotors"

.PP
См\&. определение в файле \fBSettingsForm\&.cs\fP строка \fB235\fP
.SS "float Enigma2\&.Settings\&.sound"

.PP
См\&. определение в файле \fBSettingsForm\&.cs\fP строка \fB238\fP
.SS "bool Enigma2\&.Settings\&.useM4"

.PP
См\&. определение в файле \fBSettingsForm\&.cs\fP строка \fB239\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Enigma Machine Sumulator из исходного текста\&.
