.TH "Enigma2.Plugboard" 3 "Enigma Machine Sumulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Enigma2.Plugboard
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:Microsoft\&.Xna\&.Framework\&.Game\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBPlugboard\fP ()"
.br
.in -1c
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "Dictionary< char, char > \fBreplace\fP = new Dictionary<char, char>()"
.br
.in -1c
.SS "Статические открытые данные"

.in +1c
.ti -1c
.RI "static MouseState \fBmouseOne\fP"
.br
.ti -1c
.RI "static MouseState \fBmouseTwo\fP"
.br
.in -1c
.SS "Защищенные члены"

.in +1c
.ti -1c
.RI "override void \fBLoadContent\fP ()"
.br
.ti -1c
.RI "override void \fBUpdate\fP (GameTime gameTime)"
.br
.ti -1c
.RI "override void \fBDraw\fP (GameTime gameTime)"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле \fBPlugboard\&.cs\fP строка \fB16\fP
.SH "Конструктор(ы)"
.PP 
.SS "Enigma2\&.Plugboard\&.Plugboard ()"

.PP
См\&. определение в файле \fBPlugboard\&.cs\fP строка \fB23\fP
.SH "Методы"
.PP 
.SS "override void Enigma2\&.Plugboard\&.Draw (GameTime gameTime)\fR [protected]\fP"

.PP
См\&. определение в файле \fBPlugboard\&.cs\fP строка \fB41\fP
.SS "override void Enigma2\&.Plugboard\&.LoadContent ()\fR [protected]\fP"

.PP
См\&. определение в файле \fBPlugboard\&.cs\fP строка \fB33\fP
.SS "override void Enigma2\&.Plugboard\&.Update (GameTime gameTime)\fR [protected]\fP"

.PP
См\&. определение в файле \fBPlugboard\&.cs\fP строка \fB38\fP
.SH "Данные класса"
.PP 
.SS "MouseState Enigma2\&.Plugboard\&.mouseOne\fR [static]\fP"

.PP
См\&. определение в файле \fBPlugboard\&.cs\fP строка \fB21\fP
.SS "MouseState Enigma2\&.Plugboard\&.mouseTwo\fR [static]\fP"

.PP
См\&. определение в файле \fBPlugboard\&.cs\fP строка \fB21\fP
.SS "Dictionary<char, char> Enigma2\&.Plugboard\&.replace = new Dictionary<char, char>()"

.PP
См\&. определение в файле \fBPlugboard\&.cs\fP строка \fB20\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Enigma Machine Sumulator из исходного текста\&.
