.TH "Enigma2.SettingsForm" 3 "Enigma Machine Sumulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Enigma2.SettingsForm
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:Form\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBSettingsForm\fP (\fBGameMain\fP game)"
.br
.ti -1c
.RI "void \fBCopy\fP ()"
.br
.in -1c
.SS "Защищенные члены"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле \fBSettingsForm\&.cs\fP строка \fB14\fP
.SH "Конструктор(ы)"
.PP 
.SS "Enigma2\&.SettingsForm\&.SettingsForm (\fBGameMain\fP game)"

.PP
См\&. определение в файле \fBSettingsForm\&.cs\fP строка \fB17\fP
.SH "Методы"
.PP 
.SS "void Enigma2\&.SettingsForm\&.Copy ()"

.PP
См\&. определение в файле \fBSettingsForm\&.cs\fP строка \fB63\fP
.SS "override void Enigma2\&.SettingsForm\&.Dispose (bool disposing)\fR [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBАргументы\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.PP
См\&. определение в файле \fBSettingsForm\&.Designer\&.cs\fP строка \fB14\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Enigma Machine Sumulator из исходного текста\&.
