.TH "Enigma2.ELabel" 3 "Enigma Machine Sumulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Enigma2.ELabel
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:System\&.Windows\&.Forms\&.Label\&.
.SS "Защищенные члены"

.in +1c
.ti -1c
.RI "override void \fBOnPaint\fP (System\&.Windows\&.Forms\&.PaintEventArgs e)"
.br
.in -1c
.SS "Свойства"

.in +1c
.ti -1c
.RI "int \fBRotateAngle\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBNewText\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле \fBELabel\&.cs\fP строка \fB9\fP
.SH "Методы"
.PP 
.SS "override void Enigma2\&.ELabel\&.OnPaint (System::Windows::Forms::PaintEventArgs e)\fR [protected]\fP"

.PP
См\&. определение в файле \fBELabel\&.cs\fP строка \fB13\fP
.SH "Полный список свойств"
.PP 
.SS "string Enigma2\&.ELabel\&.NewText\fR [get]\fP, \fR [set]\fP"

.PP
См\&. определение в файле \fBELabel\&.cs\fP строка \fB12\fP
.SS "int Enigma2\&.ELabel\&.RotateAngle\fR [get]\fP, \fR [set]\fP"

.PP
См\&. определение в файле \fBELabel\&.cs\fP строка \fB11\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Enigma Machine Sumulator из исходного текста\&.
