.TH "md__r_e_a_d_m_e" 3 "Enigma Machine Sumulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- Обучающее приложение 'Симулятор шифровальной машины Энигма' 
.PP

.SH "Проектная работа по предмету 'Системная и программная инженерия'"
.PP
.SH "Enigma Machine Simulator"
.PP
.SS "Введение"
Enigma Machine Simulator - это проект, предназначенный для моделирования работы оригинальной Энигмы, одной из самых известных машин шифрования, использовавшихся во время Второй мировой войны\&. Этот проект позволяет пользователям погрузиться в историю криптографии и понять, как работала эта уникальная машина\&.
.SS "Особенности"
.IP "\(bu" 2
\fBИсторическая точность\fP: Симулятор стремится воссоздать все аспекты работы оригинальной Энигмы, включая механику вращения роторов и подключение проводов\&.
.IP "\(bu" 2
\fBИнтерактивность\fP: Пользователи могут вводить текст, который затем шифруется или дешифруется с помощью машины\&.
.IP "\(bu" 2
\fBОбучающий инструмент\fP: Помогает понять принципы работы Энигмы и криптографии в целом\&.
.PP
.SS "Установка"
Для установки и запуска Enigma Machine Simulator вам потребуется:
.PP
.IP "\(bu" 2
\&.NET Core 3\&.1 или выше
.IP "\(bu" 2
Git
.PP
.IP "1." 4
Клонируйте репозиторий:
.PP
.PP
.PP
.nf
bash git clone https://github\&.com/MurkaSelebry/EnigmaMachineSimulator\&.git
.fi
.PP
.PP
.IP "2." 4
Перейдите в директорию проекта:
.PP
.PP
.PP
.nf
bash cd EnigmaMachineSimulator
.fi
.PP
.IP "3." 4
Запустите симулятор: 
.PP
.nf
bash dotnet run

.fi
.PP

.PP
.SS "Использование"
После запуска симулятора вы увидите интерфейс, который позволяет вводить текст для шифрования или дешифрования\&. Выберите режим работы (шифрование или дешифрование) и настройте параметры машины, такие как позиции роторов и подключение проводов\&.
.SS "Примеры использования"
.SS "Шифрование сообщения"
.IP "1." 4
Введите текст для шифрования в поле ввода\&.
.IP "2." 4
Настройте параметры машины, включая позиции роторов и подключение проводов\&.
.IP "3." 4
Нажмите кнопку 'Шифровать'\&.
.IP "4." 4
Полученный шифр будет отображен в поле вывода\&.
.PP
.SS "Дешифрование сообщения"
.IP "1." 4
Введите шифр для дешифрования в поле ввода\&.
.IP "2." 4
Настройте параметры машины, которые были использованы для шифрования\&.
.IP "3." 4
Нажмите кнопку 'Дешифровать'\&.
.IP "4." 4
Полученный текст будет отображен в поле вывода\&.
.PP
.SS "Дополнительная информация"
.IP "\(bu" 2
\fBДокументация\fP: Дополнительная информация о работе симулятора и его возможностях доступна в документации проекта\&.
.IP "\(bu" 2
\fBОбратная связь\fP: Если у вас возникли вопросы или предложения по улучшению симулятора, пожалуйста, свяжитесь с нами через раздел 'Issues' на GitHub\&.
.PP
.SS "Лицензия"
Этот проект распространяется под лицензией MIT\&. Подробности см\&. в файле LICENSE\&. 
